services:
  #################################################################################################################################
  # Definiert den 'pg-gvm'-Service. Dieser Container enthält eine PostgreSQL-Datenbankinstanz, 
  # die speziell für Greenbone konfiguriert ist.
  pg:
    # Das zu verwendende Image, das die für Greenbone optimierte PostgreSQL-Datenbank enthält.
    image: greenbone/pg-gvm:stable
    container_name: pg
    
    # Sorgt dafür, dass der Container automatisch neu gestartet wird, wenn er fehlschlägt.
    restart: on-failure
    
    # Bindet Speicherorte auf dem Hostsystem an den Container. Dies ermöglicht 
    # es dem Container, Datenbankdateien persistent zu speichern und auf Dateien 
    # zuzugreifen, die auf dem Hostsystem gespeichert sind.
    volumes:
      # Das Volume für die eigentlichen Datenbankdateien.
      - /docker/greenbone/volumes/psql_data_vol:/var/lib/postgresql
      # Das Volume für den PostgreSQL-Unix-Socket.
      - /docker/greenbone/volumes/psql_socket_vol:/var/run/postgresql
      #- /docker/greenbone/volumes/psql_socket_vol:/mnt_socket
  
