services:
  #################################################################################################################################
  # Definiert den 'redis-server'-Service. Dieser Container verwaltet eine Redis-Instanz, 
  # welche ein In-Memory-Datenstrukturspeicher ist und wird als Cache- und Nachrichtenbroker 
  # von verschiedenen Anwendungen, einschließlich Greenbone, verwendet.
  redis-server:

    # Das zu verwendende Image, das den Redis-Server enthält.
    image: greenbone/redis-server
    
    # Sorgt dafür, dass der Container automatisch neu gestartet wird, wenn er fehlschlägt.
    #restart: on-failure
    
    # Bindet Speicherorte auf dem Hostsystem an den Container. Dies ermöglicht 
    # es dem Container, Dateien persistent zu speichern und auf Dateien 
    # zuzugreifen, die auf dem Hostsystem gespeichert sind. 
    # Der angegebene Pfad ist typisch für die Platzierung des Redis-Unix-Sockets.
    volumes:
      #- /docker/greenbone/volumes/redis_socket_vol:/mnt
    - /docker/greenbone/volumes/redis_socket_vol:/run/redis/
      
    # Konfiguration für das Logging des Dienstes. Alle Logs von diesem 
    # Dienst werden über den syslog-Treiber an den angegebenen Socket gesendet.
    logging:
      driver: syslog
      options:
        syslog-address: "unixgram:///docker/greenbone/volumes/syslog_socket_vol/socket"
        tag: "redis-server"
